---


variables:
   GIT_SUBMODULE_STRATEGY: recursive
   TERM: dumb


stages:
  - build
  - install
  - test

image: debian:unstable

before_script:
  - apt update
  - apt install -y emacs-nox make
  - mkdir -p ~/.emacs.d


build:
  stage: build

  rules:
    - changes:
      - "*.el"
      - .gitlab-ci.yml
      - Makefile

  script:
    - make


install:
  stage: install

  rules:
    - changes:
      - "*.el"
      - .gitlab-ci.yml
      - Makefile

  script:
    - make install


test:
  stage: test
  rules:
    - changes:
      - "*.el"
      - .gitlab-ci.yml
      - Makefile

  script:
    - make test
