---


variables:
   GIT_SUBMODULE_STRATEGY: recursive
   TERM: dumb


stages:
  - build
  - test

image: debian:unstable

before_script:
  - apt update && apt install -y emacs-nox make
  - mkdir -p ~/.emacs.d


install:
  stage: build
  timeout: 10 minutes

  rules:
    - changes:
      - "*.el"
      - .gitlab-ci.yml
      - Makefile

  script:
    - make install


test:
  stage: test
  timeout: 10 minutes

  rules:
    - changes:
      - "*.el"
      - .gitlab-ci.yml
      - Makefile

  script:
    - make test
